# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-jN39V0hOXOwtyArE3MBoat_F5ZPNIP
"""

import streamlit as st
import joblib
import pandas as pd
import numpy as np
import time

# --- Configuration and Setup ---

# Set page configuration
st.set_page_config(
    page_title="Housing Market Prediction App",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Use st.cache_resource to load the model only once, improving performance.
# Update the filename if you compressed it (e.g., 'trained_model_compressed.joblib')
MODEL_FILE = 'trained_model (1).joblib'

@st.cache_resource
def load_model(file_path):
    """Loads the trained model from a joblib file."""
    try:
        model = joblib.load(file_path)
        return model
    except FileNotFoundError:
        st.error(f"Error: Model file '{file_path}' not found. "
                 "Please ensure it is in the same directory as 'app.py'.")
        return None
    except Exception as e:
        st.error(f"Error loading model: {e}")
        return None

model = load_model(MODEL_FILE)

# --- Main Application Logic ---

def predict_and_analyze(input_data_df):
    """Makes a prediction and provides context/analysis."""
    if model is None:
        return None, "Model failed to load."

    try:
        # Prediction
        prediction = model.predict(input_data_df)[0]

        # If your model predicted a log-transformed price, uncomment the line below:
        # sale_price = np.expm1(prediction)
        sale_price = prediction # Assumes prediction is in the correct currency scale

        # Simple Analysis Logic (Customize this for better insights)
        analysis_text = f"""
        **Market Analysis & Insights**

        Based on the current input features, the predicted sale price is **${sale_price:,.2f}**.

        1.  **Feature Impact:** The large **{input_data_df['Area_sqft'].iloc[0]:,} sqft** likely drives the price up.
        2.  **Age Consideration:** A property built in **{input_data_df['Year_Built'].iloc[0]}** suggests a data point factored into the price by the model.
        3.  **Note:** This prediction is a point estimate.
        """

        return sale_price, analysis_text

    except ValueError as e:
        # This usually happens if the model expects different columns than provided
        st.exception(f"Prediction Error: The model input features may be incorrect. Details: {e}")
        st.warning("Please verify that the features in the Streamlit sidebar (e.g., 'Area_sqft', 'Location') match the features your model was trained on.")
        return None, "Prediction failed due to mismatched features."
    except Exception as e:
        st.exception(f"An unexpected error occurred during prediction: {e}")
        return None, "An unexpected error occurred."


# --- Streamlit UI Components ---

st.title("🏠 Housing Price Predictor & Market Analysis")
st.markdown("Use the sidebar to input the property features and get an instant price prediction and market analysis.")

if model is None:
    st.stop() # Stop execution if model failed to load

# Sidebar for User Input
st.sidebar.header("1. Input Property Features")
st.sidebar.markdown("**🚨 Update these features to match your model's required inputs!**")

# Numerical Inputs (Placeholder features - Update these names!)
area = st.sidebar.slider("Area (Square Footage)", min_value=500, max_value=8000, value=2500, step=100, key="Area_sqft")
bedrooms = st.sidebar.slider("Number of Bedrooms", min_value=1, max_value=10, value=3, step=1, key="Bedrooms")
year = st.sidebar.slider("Year Built", min_value=1900, max_value=pd.Timestamp.now().year, value=2000, step=1, key="Year_Built")

# Categorical Input (Placeholder feature - Update this name!)
location_options = ['Urban', 'Suburban', 'Rural', 'Prime Downtown']
location = st.sidebar.selectbox("Location Type", options=location_options, key="Location")


# --- Collect and Transform Input ---

# The column names MUST match the features the model was trained with.
input_features = {
    'Area_sqft': [area],
    'Number_of_Bedrooms': [bedrooms], # Update this name if your feature is different
    'Year_Built': [year],              # Update this name if your feature is different
    'Location': [location]             # Update this name if your feature is different
}
input_df = pd.DataFrame(input_features)

st.sidebar.markdown("---")
if st.sidebar.button("Predict Price & Analyze Market", type="primary"):

    st.header("2. Prediction Result")

    with st.spinner('Calculating prediction and generating analysis...'):
        time.sleep(0.5) # Simulate processing time

        # Make Prediction
        predicted_price, analysis_output = predict_and_analyze(input_df)

        if predicted_price is not None:
            # --- Output Price ---
            st.success(f"## Predicted House Price: ${predicted_price:,.2f}")
            st.metric(label="Predicted Price", value=f"${predicted_price:,.0f}", delta="Estimated Value")

            # --- Analysis ---
            st.header("3. Housing Market Analysis")
            st.info(analysis_output)

            # Display raw inputs for verification
            st.subheader("Input Data Used for Prediction")
            st.dataframe(input_df)

        else:
             st.error("Prediction could not be completed. Check the error messages above.")

else:
    st.info("Enter the property details in the sidebar and click 'Predict Price & Analyze Market' to begin.")