# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EXEV5Z1uezxMI9S8-WofHnBzUHpSAtWM
"""

import joblib
import os
import time

# --- Configuration ---
# Name of your large, original file
INPUT_FILENAME = "trained_model (1).joblib"
# Name of the new, compressed file
OUTPUT_FILENAME = "trained_model_compressed.joblib"
# Compression level (9 is the maximum)
COMPRESSION_LEVEL = 9

def get_file_size_mb(filename):
    """Returns the file size in megabytes."""
    if os.path.exists(filename):
        return os.path.getsize(filename) / (1024 * 1024)
    return 0

try:
    print(f"--- Compression Script Started ---")

    # 1. Get initial file size
    initial_size = get_file_size_mb(INPUT_FILENAME)
    print(f"Original file size ({INPUT_FILENAME}): {initial_size:.2f} MB")

    if initial_size == 0:
         raise FileNotFoundError(f"Error: Could not find the file '{INPUT_FILENAME}' in the current directory.")

    # 2. Load the model
    print(f"\nLoading model from '{INPUT_FILENAME}'...")
    start_time = time.time()
    model = joblib.load(INPUT_FILENAME)
    load_time = time.time() - start_time
    print(f"Model loaded successfully in {load_time:.2f} seconds.")

    # 3. Re-save the model with maximum compression
    print(f"\nRe-saving model to '{OUTPUT_FILENAME}' with compress={COMPRESSION_LEVEL}...")
    start_time = time.time()
    joblib.dump(model, OUTPUT_FILENAME, compress=COMPRESSION_LEVEL)
    save_time = time.time() - start_time
    print(f"Model saved successfully in {save_time:.2f} seconds.")

    # 4. Get final file size
    final_size = get_file_size_mb(OUTPUT_FILENAME)
    print(f"\nCompressed file size ({OUTPUT_FILENAME}): {final_size:.2f} MB")

    # 5. Summary
    if final_size < initial_size:
        reduction = 100 * (1 - (final_size / initial_size))
        print(f"\nSUCCESS: File size reduced by {reduction:.2f}%.")
        print(f"The new file '{OUTPUT_FILENAME}' should now be ready for upload!")
    elif final_size == 0:
        print("ERROR: New file was not created.")
    else:
        print("NOTE: Compression did not reduce the file size. Your model may already be highly compressed.")

except FileNotFoundError as e:
    print(f"\n{e}")
    print("Please make sure the file is in the same folder as this script.")
except Exception as e:
    print(f"\nAn error occurred during processing: {e}")